apiVersion: v1
kind: Pod
metadata:
  name: etcd-server-160
spec:
  hostNetwork: true
  containers:
  - image: regis.chexiang.com:443/foundation/etcd
    name: etcd-container
    command:
    - /usr/local/bin/etcd
    - --name
    - {{ etcd_name }}
    - --initial-advertise-peer-urls
    - http://{{ ansible_default_ipv4.address }}:2380
    - --listen-peer-urls
    - http://{{ ansible_default_ipv4.address }}:2380
    - --advertise-client-urls
    - http://{{ ansible_default_ipv4.address }}:4001
    - --listen-client-urls
    - http://0.0.0.0:4001
    - --data-dir
    - /var/etcd/data
    - --initial-cluster-token
    - etcd-cluster-1
    - --initial-cluster
    - {{ etcd_init }}
    ports:
    - containerPort: 2380
      hostPort: 2380
      name: serverport
    - containerPort: 4001
      hostPort: 4001
      name: clientport
    volumeMounts:
    - mountPath: /var/etcd
      name: varetcd
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    - mountPath: /usr/share/ssl
      name: usrsharessl
      readOnly: true
    - mountPath: /var/ssl
      name: varssl
      readOnly: true
    - mountPath: /usr/ssl
      name: usrssl
      readOnly: true
    - mountPath: /usr/lib/ssl
      name: usrlibssl
      readOnly: true
    - mountPath: /usr/local/openssl
      name: usrlocalopenssl
      readOnly: true
    - mountPath: /etc/openssl
      name: etcopenssl
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etcpkitls
      readOnly: true
  volumes:
  - hostPath:
      path: /var/etcd/data
    name: varetcd
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /usr/share/ssl
    name: usrsharessl
  - hostPath:
      path: /var/ssl
    name: varssl
  - hostPath:
      path: /usr/ssl
    name: usrssl
  - hostPath:
      path: /usr/lib/ssl
    name: usrlibssl
  - hostPath:
      path: /usr/local/openssl
    name: usrlocalopenssl
  - hostPath:
      path: /etc/openssl
    name: etcopenssl
  - hostPath:
      path: /etc/pki/tls
    name: etcpkitls
